### ISSUE TITLE
Response error from Apple Sandbox

### ISSUE THREAD

**Issue by reneretz** [nomad/venice#20]
It is not related with Venice. Sometimes I am getting this response from Apple:

```
{"errorMessage":"ex.name (com.apple.jingle.foundation.exceptions.MZCodedException) -- ex.message (MZException code = newNullResponse, userInfo = { directAction = \"verifyReceipt\"; })","status":-1,"errorMessageKey":"newNullResponse"}
```

and Venice returns False

I am worried if this could happen in production servers. Should we detect this error and revalidate the receipt?

**Comment by DancinDirk** [comment]
I'm currently having this issue on a production server, did you ever find out what was causing it and how to fix it?

**Comment by rypalmer** [comment]
I'm writing comparable functionality in Python and came across this thread since I got the exact same error from Apple using the sandbox URL.
