### ISSUE TITLE
Is there a way to verify sandbox receipt?

### ISSUE THREAD

**Issue by ivanstojkovicapps** [nomad/venice#25]
Can we verify sandbox receipt?
i tried with iap verify PATH_TO_FILE --secret MY_SECRET --sandbox, but i get
no implicit conversion of String into
Integer

**Comment by mattt** [comment]
Can you post the actual backtrace?

**Comment by ivanstojkovicapps** [comment]
is there a way to show backtrace verifying from command line?
I am using auto renewable subscriptions.
The message is the same as in closed issue #12

**Comment by mattt** [comment]
You said:

> but i get no implicit conversion of String into Integer

What do you mean by that? Presumably that's an error message somewhere.

**Comment by ivanstojkovicapps** [comment]
iap verify receipt -S -p MY_KEY
returns 
"no implicit conversion of String into
Integer"

**Comment by mattt** [comment]
...and nothing else? Can you run with `--trace` and provide the full output?

**Comment by ivanstojkovicapps** [comment]
iap -t verify receipt -S -p KEY return the same

**Comment by mattt** [comment]
...

Please. Copy-paste whatever you're getting as output. I can't help you if you don't provide additional information.

**Comment by ivanstojkovicapps** [comment]
Hi Matt,
sorry for that but if you try the same command in terminal you will see. The --trace is not working and there is no backtrace for "iap -t verify receipt -S -p KEY" or with option --trace. I am going to try to call a method in an action controller.

**Comment by mattt** [comment]
Without a backtrace or any debugging information, I am unable to help you. I cannot reproduce this myself.

**Comment by mono0926** [comment]
@mattt 

This happens here:

```receipt.rb
# receipt.rb l.42
@quantity = Integer(attributes['quantity']) if attributes['quantity']
```

This is called from here:

```client.rb
# client.rb l.39
if latest_receipt_attributes = json['latest_receipt_info']
    receipt.latest = Receipt.new(latest_receipt_attributes)
end
```

`json['latest_receipt_info']` is array, so if accessed by `attributes['quantity']` raise error.

For example, change to this, error fixed, but I think this is not correct answer.

```client.rb
# client.rb
if latest_receipt_attributes = json['latest_receipt_info']
    receipt.latest = Receipt.new(latest_receipt_attributes.first) # <- first
end
```

I used receipt data got by `[[NSBundle mainBundle] appStoreReceiptURL]` as well as https://github.com/nomad/venice/issues/12#issuecomment-25316905 .
