### ISSUE TITLE
Shouldn't we know when the receipt is returned by Sandbox or Production endpoint?

### ISSUE THREAD

**Issue by reneretz** [nomad/venice#26]
In my case, it would be a check to avoid send Sandboxes tests to other systems.

**Comment by zhzenghui** [comment]
client = options.sandbox ? Venice::Client.development : Venice::Client.production
    client.shared_secret = options.secret if options.secret

     receipt = client.verify!(File.read(file))

**Comment by ObjColumnist** [comment]
Remember that Apple test your App Store Submission with Sandbox Certificates.

**Comment by leppert** [comment]
https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/AppReview.html#//apple_ref/doc/uid/TP40008267-CH10-SW1

> When validating receipts on your server, your server needs to be able to handle a production-signed app getting its receipts from Apple’s test environment. The recommended approach is for your production server to always validate receipts against the production App Store first. If validation fails with the error code “Sandbox receipt used in production”, validate against the test environment instead.
