### ISSUE TITLE
Trying to persist `receipt.original_json_response` leads to 'Stack level too deep' error

### ISSUE THREAD

**Issue by dsbonev** [nomad/venice#36]
It occurs on `receipt.original_json_response.as_json`. The receipt is auto-renewable one if that matters. 
```
pry(main)> receipt.original_json_response.as_json
SystemStackError: stack level too deep
```

The issue stems from the fact that the json is self-referencing:
```
pry(main)> receipt.original_json_response.object_id == receipt.original_json_response['receipt']['original_json_response'].object_id
=> true
```
Workaround is removing the self-referencing key:
`receipt.original_json_response['receipt'].delete 'original_json_response'`

**Comment by dankimio** [comment]
Fixed in #41.
